#!/usr/bin/python3

n = int(input())
x = 1


result = []
result.append(1)
dp = [float('inf') for _ in range(n+1)]
result = ['' for _ in range(n+1)]
dp[1] = 1
result[n] = '1'
for i in range(1,n+1):
    cnt = dp[i]
    if i * 3 <= n:
        dp[i*3] = min(cnt+1,dp[i*3])
        if min(cnt+1,dp[i*3]) == cnt+1:
            result[i*3].append(i*3)
    if i * 2 <= n:
        dp[i*2] = min(cnt+1,dp[i*2])
        if min(cnt+1,dp[i*2]) == cnt+1:
            result[i * 2].append(i * 2)
    if i + 1 <= n:
        dp[i+1] = min(cnt+1,dp[i+1])
        if min(cnt + 1,dp[i+1]) == cnt + 1:
            result[i+1].append(i+1)

print(dp[n]-1)
print(result[n])
# result.reverse()
# print(len(result))
# print(' '.join(map(str,result)))

